spring:
  datasource:
    url: jdbc:h2:mem:crypto-mall;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
  jpa:
    properties.hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
      format_sql: true
    hibernate:
      ddl-auto: create-drop


logging.level.org.hibernate:
#  SQL: DEBUG  # show SQL with TimeStamp
  type.descriptor.sql: TRACE  # show SQL binding values
#  type: TRACE  # show full action of JPA implementation

